In [1]:
# Num Py Tutorial
# import numpy library
import numpy as np

In [3]:
# creating array from list
a = np.array([1,2,3,4], float)
a

array([ 1.,  2.,  3.,  4.])

In [4]:
#manipulating array elemnts
a[:2]

array([ 1.,  2.])

In [5]:
a[1:3]

array([ 2.,  3.])

In [6]:
a[0]

1.0

In [9]:
# multi-dimensional array
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]], float)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.]])

In [10]:
a[0,0]

1.0

In [11]:
a[1:]

array([[ 5.,  6.,  7.,  8.]])

In [13]:
a[:,2]

array([ 3.,  7.])

In [16]:
a[-1:,2]

array([ 7.])

In [17]:
# shape returns a tuple with size of each array dimension
a.shape

(2, 4)

In [18]:
# dtype returns the type of the values stored in array
a.dtype

dtype('float64')

In [19]:
# len when used with array returs the length of first dimension
len(a)

2

In [20]:
# in can be used to test if  values are present in an array
2 in a

True

In [21]:
11 in a

False

In [22]:
[3, 4] in a

False

In [23]:
# arrays can be reshaped using tuples that specify new dimensions
b = np.array(range(10), float)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.]])

In [24]:
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [29]:
c = b.reshape(5,2)
c

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.]])

In [35]:
# creating list from array
ls = b.tolist()
ls
a

'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @'

In [34]:
# tostring can be used to convert the raw data in an array to binary stringa 
a
a= a.tostring()
a

AttributeError: 'str' object has no attribute 'tostring'